# Generated by Django 5.2.10 on 2026-01-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_create_tables_raw_sql'),
        ('artefacts', '0001_create_tables_raw_sql'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS evidence(ArtefactId INTEGER, ExhibitId INTEGER, PRIMARY KEY (ArtefactId, ExhibitId), FOREIGN KEY (ArtefactId) REFERENCES artefacts(ArtefactId), FOREIGN KEY (ExhibitId) REFERENCES exhibits(ExhibitId));",
            reverse_sql="DROP TABLE IF EXISTS evidence;"
        )
    ]
