# Generated by Django 5.2.10 on 2026-01-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_tables_raw_sql'),
        ('exhibits', '0001_create_tables_raw_sql')
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS book_marks(UserId INTEGER PRIMARY KEY, ExhibitId INTEGER, FOREIGN KEY (UserId) REFERENCES users(UserId), FOREIGN KEY (ExhibitId) REFERENCES exhibits(ExhibitId));",
            reverse_sql="DROP TABLE IF EXISTS book_marks;"
        )
    ]
