# Generated by Django 5.2.10 on 2026-01-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_tables_raw_sql'),
        ('quizzes', '0001_create_tables_raw_sql'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS attempted_quizzes(UserId INTEGER, QuizId INTEGER, PointsGained INTEGER, AttemptDate DATE, PRIMARY KEY (UserId, QuizId), FOREIGN KEY (UserId) REFERENCES users(UserId), FOREIGN KEY (QuizId) REFERENCES quizzes(QuizId));",
            reverse_sql="DROP TABLE IF EXISTS attempted_quizzes;"
        )
    ]
