# Generated by Django 5.2.10 on 2026-01-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_create_tables_raw_sql'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS contributing_factors(ContributingFactorId INTEGER PRIMARY KEY, ExhibitId INTEGER, DataIssues TEXT, DesignChoices TEXT, OrganisationalOrGovernanceIssues TEXT, FOREIGN KEY (ExhibitId) REFERENCES exhibits(ExhibitId));",
            reverse_sql="DROP TABLE IF EXISTS contributing_factors;"
        )
    ]
