# Generated by Django 5.2.10 on 2026-01-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_create_tables_raw_sql'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS quizz_questions(QuestionId INTEGER PRIMARY KEY, QuizId INTEGER, Question TEXT, QuestionAnswer TEXT,CompletionRate INTEGER,AttemptRate INTEGER,Points INTEGER, FOREIGN KEY (QuizId) REFERENCES quizzes(QuizId));",
            reverse_sql="DROP TABLE IF EXISTS quizz_questions;"
        )
    ]
