# Generated by Django 5.2.10 on 2026-01-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS users(UserId INTEGER PRIMARY KEY, User_Level INTEGER NOT NULL, FName VARCHAR(255),LName VARCHAR(255),Password VARCHAR(255), TotalQuizzPoints INTEGER);",
            reverse_sql="DROP TABLE IF EXISTS users;"
        )
    ]
