# Generated by Django 5.2.10 on 2026-01-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_create_tables_raw_sql'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS quizzes(QuizId INTEGER PRIMARY KEY,ExhibitId INTEGER, QuizzDetails TEXT, CompletionRate INTEGER, AttemptRate INTEGER,TotalQuestionPoints INTEGER, FOREIGN KEY (ExhibitId) REFERENCES exhibits(ExhibitId));",
            reverse_sql="DROP TABLE IF EXISTS quizzes;"
        )
    ]
