# Generated by Django 5.2.10 on 2026-01-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(sql =
        "CREATE TABLE IF NOT EXISTS artefacts(ArtefactId INTEGER PRIMARY KEY, Info VARCHAR(255), ArtefactDate DATE,ArtefactObjectPath TEXT);",
        reverse_sql="DROP TABLE IF EXISTS artefacts;" )
    ]
