# Generated by Django 5.2.10 on 2026-01-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS exhibits(ExhibitId INTEGER PRIMARY KEY,Title TEXT, Domain TEXT, BackgroundDeploymentContext TEXT, IntededUse TEXT, ViewNumber INTEGER);",
            reverse_sql="DROP TABLE IF EXISTS exhibits;"
        )
    ]
    
    
